name: This is a bug
description: Tell me your bugs
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - mishmanners
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
